name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11'

    - name: Install Dependencies
      run: npm install

    - name: Build Chrome Extension
      run: npm run build

    - name: Extract Version Tag
      id: get_version
      run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
      env:
        GITHUB_REF: ${{ github.ref }}

    - name: Archive Production Artifact
      run: zip -r release-${{ steps.get_version.outputs.tag }}.zip ./build

    - name: Upload Release Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./yanorama-${{ steps.get_version.outputs.tag }}.zip
        asset_name: yanorama-${{ steps.get_version.outputs.tag }}.zip
        asset_content_type: application/zip
