name: Build and Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11'

    - name: Install Dependencies
      run: npm install

    - name: Build Chrome Extension
      run: npm run build

    - name: Archive Production Artifact
      run: zip -r yanorama-${{  github.ref_name }}.zip ./build


    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: yanorama-${{  github.ref_name }}.zip
